### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [41, 4, 4]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead.

### ISSUE THREAD

**Issue by zeyutt** [yaochih/GCVD-release#2]
Hi, thanks for the excellent work. However, during test as proposed  "python3 main.py test-dataset/chess/seq-01.mkv --name test --pose_graph", I encountered a runtime error. It seems untraceable even when I set detect_anomally to "True". Has anyone encountered the same problem? Here are the outputs in the shell.
``` shell
=>Load models
  Loading weights: weights/models/midas_v21-f6b98070.pt
=>Reconstruct keyframes
    0%|                    | 0/1200 [00:00<?Traceback (most recent call last):
  File "main.py", line 249, in <module>
    vd.process_keyframes()
  File "main.py", line 82, in process_keyframes
    keyframes = self.sfm.reconstruct_images(
  File "/home/pc/GCVD-release/sfm.py", line 113, in reconstruct_images
    loss['full'].backward()
  File "/home/pc/.conda/envs/GCVD/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/pc/.conda/envs/GCVD/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [41, 4, 4]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
    0%|                    | 0/1200 [00:01<?
```

**Comment by zeyutt** [comment]
Seems inverse mat function in torch 1.12 version appear to be inplace op. (Maybe not right  :! )

**Comment by zeyutt** [comment]
However，the pose optimization result seems not right

**Comment by Lwy-1998** [comment]
I had the same problem ,How did you solve it?

**Comment by jiangyijin** [comment]
I had the same problem ,How did you solve it?
