### ISSUE TITLE
Reproducing depth estimation metrics

### ISSUE THREAD

**Issue by Mixanik-43** [yaochih/GCVD-release#3]
Hi, thank you for the great work!
I've tried to reproduce the results you've published for TUM and 7 scenes datasets. However, the depth estimation metric (abs rel) values I obtained are significantly worse then the ones reported in the paper.
For 7_scenes/chess/seq-01 sequence I got abs rel = 0.83 with the command you provided in Readme:
`python3 main.py test-dataset/chess/seq-01.mkv --name test --pose_graph`. I tried using `--post_filter` as well, but it did not change the result significantly. You reported abs rel = 0.124 on 7 scenes, so I suppose you had << 83% relative error on chess/seq-01.

For TUM/freiburg1_desk I got 0.2718 relative error, while you reported 0.0940 for this sequence.

I tried to find the reason of the high depth estimation errors. It seems like GCVD depth estimates often have wrong scale. If I adjust scales to the estimated depth maps to match **ground truth** depth (individual constant scale for each frame), I can get 0.0897 relative error for TUM/freiburg1_desk sequence, which seems to be a reasonable result, therfore correcting the wrong scale could potentially lead to the results reported in the paper.
Here is an example of a frame from TUM/freiburg1_desk where GCVD output has high relative error (0.507). In the original TUM dataset its name is rgbd_dataset_freiburg1_desk/rgb/1305031464.759740.png
![image](https://user-images.githubusercontent.com/38531267/219682356-890c8f52-1102-42d7-a3f4-bf162a12586e.png)

As you can see, GCVD output has a reasonable structure, but the scale is wrong, which affects abs rel metric.

I used the files that `main.py` script generated in `outputs/test/depths/final` directory (or `outputs/test/depths/filtered` for runs with `--post_filter` option) as the final output of GCVD algorithm. Is it right, or should I additionally scale these depth maps somehow?
Should the command `python3 main.py video.mkv --name test --pose_graph --post_filter` reproduce the result reported in the paper or should I use some additional options? Are there any other tips for reproducing these results?

**Comment by Mixanik-43** [comment]
Adding `--mesh_deformation` slightly improved the result (*0.25* abs rel on TUM/freiburg1_desk sequence)
Adding more options from the GCVD paper (`python3 main.py video.mkv --name test --pose_graph --post_filter --mesh_deformation --num_epoch_edge 100 --keyframe_scales 4 --loss_smooth 0.1`) increased abs rel on this sequence to *0.34*, which is far from the reported *0.094* abs rel.
So @yaochih, could you please provide the correct command to reproduce GCVD paper results, or could you share your metric evaluation script? Originally MiDaS evaluates abs rel after adjusting inverse depth shift and scale. I thought, since GCVD estimates scales, you do not use such adjustment in metric evaluation. Is that right?

**Comment by Mixanik-43** [comment]
It seems like depth scale is adjusted to match ground truth. Here is the corresponding part in the arxiv paper:
![image](https://user-images.githubusercontent.com/38531267/222760602-0f1c0e1d-dc08-4e79-a852-55710478b08a.png)
Now I obtained metrics comparable to the reported ones!
However, I still did not manage to find options that would reproduce the reported metrics exactly.

**Comment by mathidot** [comment]
> It seems like depth scale is adjusted to match ground truth. Here is the corresponding part in the arxiv paper: ![image](https://user-images.githubusercontent.com/38531267/222760602-0f1c0e1d-dc08-4e79-a852-55710478b08a.png) Now I obtained metrics comparable to the reported ones! However, I still did not manage to find options that would reproduce the reported metrics exactly.

Could you please share your test code with me? Thank you.

**Comment by jiangyijin** [comment]
Hello, I encountered the following problem while running, could you please tell me how to solve it?

 python 3 main.py test-dataset/chess/seq-01.mkv --name test --pose_graph
=>Preprocess video
  =======================================
  | Video INFO                          |
  | Path: test-dataset/chess/seq-01.mkv |
  | Number of frames: 1000              |
  | Frame rate: 25.0  
 | Frame size: (480, 640)              |
  =======================================
  =========================
  | Downsample INFO       |
  | Original: (480, 640)  |
  | For flow: (512, 640)  |
  | For depth: (288, 384) |
  =========================
dynamic frames input paths: [Path('outputs/test/images/*.png')]
100%|███████████████████████████████████████| 1000/1000 [02:22<00:00,  7.00it/s]
Initialize
Device: cuda
model_type 'midas_v21' not implemented, use: --model_type large
Traceback (most recent call last):
  File "/data/GCVD-release/MiDaS/run.py", line 276, in <module>
    run(args.input_path, args.output_path, args.model_weights, args.model_type, args.optimize, args.side, args.height,
  File "/data/GCVD-release/MiDaS/run.py", line 126, in run
    model, transform, net_w, net_h = load_model(device, model_path, model_type, optimize, height, square)
  File "/data/GCVD-release/MiDaS/midas/model_loader.py", line 199, in load_model
    assert False
AssertionError

**Comment by jiangyijin** [comment]
ubuntu@ml-ubuntu20-04-desktop-v1-0-108gb-100m:/data/GCVD-release$ python3 main.py test-dataset/chess/seq-01.mkv --name test --pose_graph
=>Preprocess video
  =======================================
  | Video INFO                          |
  | Path: test-dataset/chess/seq-01.mkv |
  | Number of frames: 1000              |
  | Frame rate: 25.0                    |
  | Frame size: (480, 640)              |
  =======================================
  =========================
  | Downsample INFO       |
  | Original: (480, 640)  |
  | For flow: (512, 640)  |
  | For depth: (288, 384) |
  =========================
dynamic frames input paths: [Path('outputs/test/images/*.png')]
100%|███████████████████████████████████████| 1000/1000 [02:22<00:00,  7.00it/s]
Initialize
Device: cuda
model_type 'midas_v21' not implemented, use: --model_type large
Traceback (most recent call last):
  File "/data/GCVD-release/MiDaS/run.py", line 276, in <module>
    run(args.input_path, args.output_path, args.model_weights, args.model_type, args.optimize, args.side, args.height,
  File "/data/GCVD-release/MiDaS/run.py", line 126, in run
    model, transform, net_w, net_h = load_model(device, model_path, model_type, optimize, height, square)
  File "/data/GCVD-release/MiDaS/midas/model_loader.py", line 199, in load_model
    assert False
AssertionError
  100%|████████████████████| 999/999 [03:18<00:00
  Keyframe decision
  100%|███████████████████▉| 997/1000 [00:31<00:00  Number of Keyframes: 135
  ============================================================================
  | Keyframes indexs:                                                        |
  | [  0  18  32  46  58  68  81  91 103 114 127 136 143 151 159 167 174 179 |
  |  185 191 199 207 215 221 230 239 248 256 264 272 279 286 292 301 308 317 |
  |  325 331 337 341 344 348 352 358 361 365 371 380 386 394 405 410 413 415 |
  |  420 425 430 436 445 452 460 465 474 482 490 497 501 503 506 509 512 516 |
  |  519 523 526 529 532 536 539 543 549 555 559 565 574 583 592 602 613 622 |
  |  632 639 646 653 660 666 676 682 690 698 706 714 722 728 734 738 744 750 |
  |  758 767 774 783 790 799 809 817 824 828 834 842 851 862 875 889 898 908 |
  |  919 929 939 947 957 969 981 993 999]                                    |
  ============================================================================
  100%|████████████████████| 134/134 [00:43<00:0000
  Number of Keyframes: 135█| 134/134 [00:43<00:00
  ============================================================================
  | Keyframes indexs:                                                        |
  | [  0  18  32  46  58  68  81  91 103 114 127 136 143 151 159 167 174 179 |
  |  185 191 199 207 215 221 230 239 248 256 264 272 279 286 292 301 308 317 |
  |  325 331 337 341 344 348 352 358 361 365 371 380 386 394 405 410 413 415 |
  |  420 425 430 436 445 452 460 465 474 482 490 497 501 503 506 509 512 516 |
  |  519 523 526 529 532 536 539 543 549 555 559 565 574 583 592 602 613 622 |
  |  632 639 646 653 660 666 676 682 690 698 706 714 722 728 734 738 744 750 |
  |  758 767 774 783 790 799 809 817 824 828 834 842 851 862 875 889 898 908 |
  |  919 929 939 947 957 969 981 993 999]                                    |
  ============================================================================
=>Load models
  Loading weights: weights/models/midas_v21-f6b98070.pt
=>Reconstruct keyframes
  100%|████████████████████| 1000/1000 [01:18<00:00
Traceback (most recent call last):0 [00:00<?
  File "/data/GCVD-release/main.py", line 246, in <module>
    vd.process_keyframes()
  File "/data/GCVD-release/main.py", line 62, in process_keyframes
    keyframes = self.seq_io.get_items(indices, 
  File "/home/ubuntu/anaconda3/envs/3dgs/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/GCVD-release/sequence_io.py", line 417, in get_items
    items['gt_depth'] = self.load_target_depths(indices, load_size=load_size)
  File "/data/GCVD-release/sequence_io.py", line 321, in load_target_depths
    depth = self.load_target_depth(i, load_size=load_size)
  File "/data/GCVD-release/sequence_io.py", line 307, in load_target_depth
    depth = imread(self.gt_depth_paths[index])
IndexError: list index out of range
    0%|                    | 0/1200 [00:00<?
