### ISSUE TITLE
ValueError:setting an array element with a sequence. 

### ISSUE THREAD

**Issue by Lwy-1998** [yaochih/GCVD-release#4]
I got a problem when I run testing code.
The platform is  ubuntu22.04  cuda11.1 pytorch1.8.0 python3.8
I guess this is due to numpy version?
```
=>Reconstruct keyframes
  100%|████████████████████| 1200/1200 [02:50<00:00Traceback (most recent call last):
  File "main.py", line 246, in <module>
    vd.process_keyframes()
  File "main.py", line 101, in process_keyframes
    np.save(self.seq_io.root/'keyframe_groups.npy', keyframe_groups)
  File "<__array_function__ internals>", line 200, in save
  File "/home/lwy/.conda/envs/gcvd/lib/python3.8/site-packages/numpy/lib/npyio.py", line 521, in save
    arr = np.asanyarray(arr)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
  100%|████████████████████| 1200/1200 [02:52<00:00
```

**Comment by Lwy-1998** [comment]
This problem is solved by downgrading to numpy=1.21.4
